services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - PAYMENT_SERVICE_URL=${PAYMENT_SERVICE_URL}
      - OPERATION_SERVICE_URL=${OPERATION_SERVICE_URL}
      - UPLOAD_DIR=/app/uploads
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - uploads-data:/app/uploads
    networks:
      - db-network

volumes:
  uploads-data:

networks:
  db-network:
    driver: bridge
